---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
      app: book-import
  name: book-import-placement-0
  namespace: book-import
spec:
  clusterSelector:
    matchLabels:
      'env': 'prod'
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
