---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: book-import/app
  labels:
    app: book-import
  name: book-import
  namespace: book-import
spec:
    channel: application-samples/gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: book-import-placement-0
