apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clouds-app-qa
  namespace: openshift-gitops
spec:
  project: clouds-api
  source:
    repoURL: 'https://github.com/pecorawal/multicluster-pipeline.git'
    path: gitops-kustomize/overlays/qa
    targetRevision: qa
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
